language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t ashboro/udemydockerreact  -f Dockerfile.dev .

script:
  - docker run -e CI=true ashboro/udemydockerreact  npm run test
  
  
